version: '3.9'
networks:
  wordpressnet:
    driver: bridge
volumes:
  wordpress:
  db:

services:
  wordpress:
    image: wordpress
    container_name: wordpress
    depends_on:
      - db
    networks:
      - wordpressnet
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_DB_NAME: desafio5
    volumes:
      - wordpress:/var/www/html
  db:
    image: mysql:5.7
    container_name: mysql
    networks:
      - wordpressnet
    environment:
      MYSQL_DATABASE: desafio5
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql